trigger:
-  main
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  ENV: 'qa'
  BROWSER: 'chromium'

stages:
- stage: Test
  displayName: 'Run Tests'
  jobs:
  - job: PlaywrightTests
    displayName: 'Playwright Tests'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        npm ci
        npx playwright install
      displayName: 'Install dependencies'

    - script: |
        npm run test
      env:
        ENV: $(ENV)
        BROWSER: $(BROWSER)
      displayName: 'Run Playwright tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'test-results/junit.xml'
        failTaskOnFailedTests: false
      displayName: 'Publish test results'

    - script: |
        npm install -g allure-commandline
        allure generate allure-results --clean -o allure-report
      displayName: 'Generate Allure report'

    - task: PublishHtmlReport@1
      inputs:
        reportDir: 'allure-report'
        tabName: 'Allure Report'
      displayName: 'Publish Allure report'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'test-results'
        artifactName: 'test-results'
      displayName: 'Publish test artifacts'
      condition: always()

  - job: ParallelTests
    displayName: 'Parallel Browser Tests'
    strategy:
      matrix:
        Chrome:
          BROWSER: 'chromium'
        Firefox:
          BROWSER: 'firefox'
        Safari:
          BROWSER: 'webkit'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'

    - script: |
        npm ci
        npx playwright install
      displayName: 'Install dependencies'

    - script: |
        npm run test
      env:
        ENV: $(ENV)
        BROWSER: $(BROWSER)
      displayName: 'Run tests on $(BROWSER)'
 